source = ~/.config/hypr/bindings/variables.conf

# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
bind = $mainMod, grave, exec, zeditor ~/.config/hypr
bind = $mainMod, T, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, escape, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, space, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle
bind = $mainMod, B, exec, $browser
bind = $mainMod ALT, B, exec, env -u WAYLAND_DISPLAY firefox
bind = $mainMod, L, exec, hyprlock
bind = $mainMod ALT, L, exec, systemctl suspend
bind = $mainMod, Z, exec, $proxy & dunstify "proxy" "enabled"
bind = $mainMod ALT, Z, exec, $killProxy & dunstify "proxy" "disabled"
bind = $mainMod, M, exec, $spotify
bind = $mainMod CONTROL, C, exec, hyprpicker -a
bind = SUPER, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind = SUPER_ALT, V, exec, cliphist wipe
bind = $mainMod ALT, K, exec, QT_QPA_PLATFORM=xcb nemo
bind = $mainMod ALT, A, exec, env -u WAYLAND_DISPLAY /home/pryniki/.appimages/PureRef-2.1.0.beta2_x64.Appimage

# xkill alternative
bind = $mainMod ALT, C, exec, hyprctl kill

# hypridle
bind = $mainMod, I, exec, hypridle & disown && dunstify "sleep" "enabled"
bind = $mainMod ALT, I, exec, killall hypridle & dunstify "sleep" "disabled"

# screenshot
 bind =, Print, exec, grim -g "$(slurp)" - | wl-copy && wl-paste > ~/pictures/screenshots/screenshot-$(date +%F_%T).png | dunstify "Screenshot of the region taken" -t 1000 # screenshot of a region
